# Generated by Django 5.2.1 on 2025-06-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_alter_colors_color_alter_colors_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colors',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='colors',
            name='color',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
